name: dry-system
codacy_id: 3a0e30d0ae2542c7ba047ba5f923c0bb
gemspec:
  authors: ["Piotr Solnica"]
  email: ["piotr.solnica@gmail.com"]
  summary: "Organize your code into reusable components"
  runtime_dependencies:
    - [dry-auto_inject, "~> 1.1"]
    - [dry-core, "~> 1.1"]
    - [dry-configurable, "~> 1.3"]
    - [dry-inflector, "~> 1.1"]
